### ISSUE TITLE
startShowinng() method in MovieList class does not compile.

### ISSUE THREAD

**Issue by adamthecreator369** [adamthecreator369/Movie_Management_System#1]
Neha, please rewrite and test your code for this method. Here is the error message that occurs when this method is called.

Exception in thread "main" java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:911)
	at java.util.ArrayList$Itr.next(ArrayList.java:861)
	at movies.lists.MovieList.startShowing(MovieList.java:159)
	at movies.manager.ManagementSystem.main(ManagementSystem.java:191)

**Comment by adamthecreator369** [comment]
Hint: Is removing an element while the list is being iterated over by an iterator permissible?

**Comment by adamthecreator369** [comment]
I wrote the code for you if you want you can use my version: 

	`public void startShowing(Date d) {
		Iterator<Movie> it = comingMovies.iterator(); // Create iterator to iterate over the comingMovies list
		ArrayList<Integer> removePos = new ArrayList<>();
		while (it.hasNext()) { // While there are more elements to iterate over
			Movie currMovie = it.next(); // Move the iterator to the next element and store the element that was passed over
			if (currMovie.getReleaseDate().compareTo(d) == 0) { // If the current movie has the same target release date
				addToShowingList(currMovie); // Add this movie to the showingMovies list
				currMovie.setStatus(MovieStatus.Showing); // Change the status from received to released
				// Add the index position of the movie with the matching date to be changed to the list. 
				removePos.add(comingMovies.indexOf(currMovie));
			} 
		}
		
		if (removePos.size() == 0) { System.out.println("No movies with that release date  the status \"Coming\"."); }
		// Remove all elements to be transfered from the list if any exist. Otherwise notify user that they do not exist. 
		while (removePos.size() != 0)  { 
			// Notify the user which movie's have been changed. 
			System.out.println(comingMovies.get(removePos.get(0)).getName() + " started showing successfully.");	
			// Now remove this movie from the comingMovies list because it's been transferred to the showingMovies list
			comingMovies.remove(comingMovies.get(removePos.get(0))); 
			// Now remove the current index position from the list of positions to be removed. 
			removePos.remove(0);
		} 
		
	}`

**Comment by adamthecreator369** [comment]
I have replaced the old code with the code from the above comment. Issue has been resolved.
